// Package contracts provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package contracts

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ConfigType.
const (
	ConfigTypeAppSelector   ConfigType = "app-selector"
	ConfigTypeArrayTools    ConfigType = "array[tools]"
	ConfigTypeBoolean       ConfigType = "boolean"
	ConfigTypeModelSelector ConfigType = "model-selector"
	ConfigTypeSecretInput   ConfigType = "secret-input"
	ConfigTypeSelect        ConfigType = "select"
	ConfigTypeTextInput     ConfigType = "text-input"
)

// Valid indicates whether the value is a known member of the ConfigType enum.
func (e ConfigType) Valid() bool {
	switch e {
	case ConfigTypeAppSelector:
		return true
	case ConfigTypeArrayTools:
		return true
	case ConfigTypeBoolean:
		return true
	case ConfigTypeModelSelector:
		return true
	case ConfigTypeSecretInput:
		return true
	case ConfigTypeSelect:
		return true
	case ConfigTypeTextInput:
		return true
	default:
		return false
	}
}

// Defines values for GetToolSuccessResponseCode.
const (
	GetToolSuccessResponseCodeN0 GetToolSuccessResponseCode = 0
)

// Valid indicates whether the value is a known member of the GetToolSuccessResponseCode enum.
func (e GetToolSuccessResponseCode) Valid() bool {
	switch e {
	case GetToolSuccessResponseCodeN0:
		return true
	default:
		return false
	}
}

// Defines values for GetToolSuccessResponseMessage.
const (
	GetToolSuccessResponseMessageSuccess GetToolSuccessResponseMessage = "success"
)

// Valid indicates whether the value is a known member of the GetToolSuccessResponseMessage enum.
func (e GetToolSuccessResponseMessage) Valid() bool {
	switch e {
	case GetToolSuccessResponseMessageSuccess:
		return true
	default:
		return false
	}
}

// Defines values for ListToolsSuccessResponseCode.
const (
	ListToolsSuccessResponseCodeN0 ListToolsSuccessResponseCode = 0
)

// Valid indicates whether the value is a known member of the ListToolsSuccessResponseCode enum.
func (e ListToolsSuccessResponseCode) Valid() bool {
	switch e {
	case ListToolsSuccessResponseCodeN0:
		return true
	default:
		return false
	}
}

// Defines values for ListToolsSuccessResponseMessage.
const (
	ListToolsSuccessResponseMessageSuccess ListToolsSuccessResponseMessage = "success"
)

// Valid indicates whether the value is a known member of the ListToolsSuccessResponseMessage enum.
func (e ListToolsSuccessResponseMessage) Valid() bool {
	switch e {
	case ListToolsSuccessResponseMessageSuccess:
		return true
	default:
		return false
	}
}

// Defines values for ParameterAutoGenerateType.
const (
	PromptInstruction ParameterAutoGenerateType = "prompt_instruction"
)

// Valid indicates whether the value is a known member of the ParameterAutoGenerateType enum.
func (e ParameterAutoGenerateType) Valid() bool {
	switch e {
	case PromptInstruction:
		return true
	default:
		return false
	}
}

// Defines values for PluginTag.
const (
	Agent         PluginTag = "agent"
	Business      PluginTag = "business"
	Design        PluginTag = "design"
	Education     PluginTag = "education"
	Entertainment PluginTag = "entertainment"
	Finance       PluginTag = "finance"
	Image         PluginTag = "image"
	Medical       PluginTag = "medical"
	News          PluginTag = "news"
	Other         PluginTag = "other"
	Productivity  PluginTag = "productivity"
	Rag           PluginTag = "rag"
	Search        PluginTag = "search"
	Social        PluginTag = "social"
	Travel        PluginTag = "travel"
	Trigger       PluginTag = "trigger"
	Utilities     PluginTag = "utilities"
	Videos        PluginTag = "videos"
	Weather       PluginTag = "weather"
)

// Valid indicates whether the value is a known member of the PluginTag enum.
func (e PluginTag) Valid() bool {
	switch e {
	case Agent:
		return true
	case Business:
		return true
	case Design:
		return true
	case Education:
		return true
	case Entertainment:
		return true
	case Finance:
		return true
	case Image:
		return true
	case Medical:
		return true
	case News:
		return true
	case Other:
		return true
	case Productivity:
		return true
	case Rag:
		return true
	case Search:
		return true
	case Social:
		return true
	case Travel:
		return true
	case Trigger:
		return true
	case Utilities:
		return true
	case Videos:
		return true
	case Weather:
		return true
	default:
		return false
	}
}

// Defines values for ToolParameterForm.
const (
	Form   ToolParameterForm = "form"
	Llm    ToolParameterForm = "llm"
	Schema ToolParameterForm = "schema"
)

// Valid indicates whether the value is a known member of the ToolParameterForm enum.
func (e ToolParameterForm) Valid() bool {
	switch e {
	case Form:
		return true
	case Llm:
		return true
	case Schema:
		return true
	default:
		return false
	}
}

// Defines values for ToolParameterType.
const (
	ToolParameterTypeAny           ToolParameterType = "any"
	ToolParameterTypeAppSelector   ToolParameterType = "app-selector"
	ToolParameterTypeArray         ToolParameterType = "array"
	ToolParameterTypeBoolean       ToolParameterType = "boolean"
	ToolParameterTypeCheckbox      ToolParameterType = "checkbox"
	ToolParameterTypeDate          ToolParameterType = "date"
	ToolParameterTypeDateRange     ToolParameterType = "date-range"
	ToolParameterTypeDynamicSelect ToolParameterType = "dynamic-select"
	ToolParameterTypeFile          ToolParameterType = "file"
	ToolParameterTypeFiles         ToolParameterType = "files"
	ToolParameterTypeModelSelector ToolParameterType = "model-selector"
	ToolParameterTypeNumber        ToolParameterType = "number"
	ToolParameterTypeObject        ToolParameterType = "object"
	ToolParameterTypeSecretInput   ToolParameterType = "secret-input"
	ToolParameterTypeSelect        ToolParameterType = "select"
	ToolParameterTypeString        ToolParameterType = "string"
)

// Valid indicates whether the value is a known member of the ToolParameterType enum.
func (e ToolParameterType) Valid() bool {
	switch e {
	case ToolParameterTypeAny:
		return true
	case ToolParameterTypeAppSelector:
		return true
	case ToolParameterTypeArray:
		return true
	case ToolParameterTypeBoolean:
		return true
	case ToolParameterTypeCheckbox:
		return true
	case ToolParameterTypeDate:
		return true
	case ToolParameterTypeDateRange:
		return true
	case ToolParameterTypeDynamicSelect:
		return true
	case ToolParameterTypeFile:
		return true
	case ToolParameterTypeFiles:
		return true
	case ToolParameterTypeModelSelector:
		return true
	case ToolParameterTypeNumber:
		return true
	case ToolParameterTypeObject:
		return true
	case ToolParameterTypeSecretInput:
		return true
	case ToolParameterTypeSelect:
		return true
	case ToolParameterTypeString:
		return true
	default:
		return false
	}
}

// ConfigOption defines model for ConfigOption.
type ConfigOption struct {
	Label I18NObject `json:"label"`
	Value string     `json:"value"`
}

// ConfigType defines model for ConfigType.
type ConfigType string

// DaemonErrorResponse defines model for DaemonErrorResponse.
type DaemonErrorResponse struct {
	Code int `json:"code"`
	Data any `json:"data"`

	// Message JSON-encoded daemon error details, retained as a string for compatibility.
	Message string `json:"message"`
}

// GetToolResponse defines model for GetToolResponse.
type GetToolResponse struct {
	union json.RawMessage
}

// GetToolSuccessResponse defines model for GetToolSuccessResponse.
type GetToolSuccessResponse struct {
	Code    GetToolSuccessResponseCode    `json:"code"`
	Data    ToolProviderInstallation      `json:"data"`
	Message GetToolSuccessResponseMessage `json:"message"`
}

// GetToolSuccessResponseCode defines model for GetToolSuccessResponse.Code.
type GetToolSuccessResponseCode int

// GetToolSuccessResponseMessage defines model for GetToolSuccessResponse.Message.
type GetToolSuccessResponseMessage string

// I18NObject defines model for I18nObject.
type I18NObject struct {
	EnUS   string  `json:"en_US"`
	JaJP   *string `json:"ja_JP,omitempty"`
	PtBR   *string `json:"pt_BR,omitempty"`
	ZhHans *string `json:"zh_Hans,omitempty"`
}

// ListToolsResponse defines model for ListToolsResponse.
type ListToolsResponse struct {
	union json.RawMessage
}

// ListToolsSuccessResponse defines model for ListToolsSuccessResponse.
type ListToolsSuccessResponse struct {
	Code    ListToolsSuccessResponseCode    `json:"code"`
	Data    []ToolProviderInstallation      `json:"data"`
	Message ListToolsSuccessResponseMessage `json:"message"`
}

// ListToolsSuccessResponseCode defines model for ListToolsSuccessResponse.Code.
type ListToolsSuccessResponseCode int

// ListToolsSuccessResponseMessage defines model for ListToolsSuccessResponse.Message.
type ListToolsSuccessResponseMessage string

// NullableI18NObject defines model for NullableI18nObject.
type NullableI18NObject = I18NObject

// OAuthSchema defines model for OAuthSchema.
type OAuthSchema struct {
	ClientSchema      *[]ProviderConfig `json:"client_schema"`
	CredentialsSchema *[]ProviderConfig `json:"credentials_schema"`
}

// ParameterAutoGenerate defines model for ParameterAutoGenerate.
type ParameterAutoGenerate struct {
	Type ParameterAutoGenerateType `json:"type"`
}

// ParameterAutoGenerateType defines model for ParameterAutoGenerate.Type.
type ParameterAutoGenerateType string

// ParameterOption defines model for ParameterOption.
type ParameterOption struct {
	Icon  string     `json:"icon"`
	Label I18NObject `json:"label"`
	Value string     `json:"value"`
}

// ParameterTemplate defines model for ParameterTemplate.
type ParameterTemplate struct {
	Enabled bool `json:"enabled"`
}

// PluginTag defines model for PluginTag.
type PluginTag string

// ProviderConfig defines model for ProviderConfig.
type ProviderConfig struct {
	// Default A scalar credential default, or null when no default is configured.
	Default       any                 `json:"default"`
	Help          *NullableI18NObject `json:"help"`
	Label         I18NObject          `json:"label"`
	Multiple      bool                `json:"multiple"`
	Name          string              `json:"name"`
	Options       *[]ConfigOption     `json:"options"`
	Placeholder   *NullableI18NObject `json:"placeholder"`
	Required      bool                `json:"required"`
	ResetOnChange *ResetOnChange      `json:"reset_on_change,omitempty"`
	Scope         *string             `json:"scope"`
	Type          ConfigType          `json:"type"`
	URL           *string             `json:"url"`
}

// ResetOnChange defines model for ResetOnChange.
type ResetOnChange = []string

// ToolDeclaration defines model for ToolDeclaration.
type ToolDeclaration struct {
	Description          ToolDescription         `json:"description"`
	HasRuntimeParameters bool                    `json:"has_runtime_parameters"`
	Identity             ToolIdentity            `json:"identity"`
	OutputSchema         *map[string]interface{} `json:"output_schema,omitempty"`
	Parameters           *[]ToolParameter        `json:"parameters"`
}

// ToolDescription defines model for ToolDescription.
type ToolDescription struct {
	Human I18NObject `json:"human"`
	Llm   string     `json:"llm"`
}

// ToolIdentity defines model for ToolIdentity.
type ToolIdentity struct {
	Author string     `json:"author"`
	Label  I18NObject `json:"label"`
	Name   string     `json:"name"`
}

// ToolParameter defines model for ToolParameter.
type ToolParameter struct {
	AutoGenerate *ParameterAutoGenerate `json:"auto_generate"`

	// Default Any JSON value, including null, arrays, and objects.
	Default          any                `json:"default"`
	Form             ToolParameterForm  `json:"form"`
	HumanDescription I18NObject         `json:"human_description"`
	Label            I18NObject         `json:"label"`
	LlmDescription   string             `json:"llm_description"`
	Max              *float64           `json:"max"`
	Min              *float64           `json:"min"`
	Multiple         bool               `json:"multiple"`
	Name             string             `json:"name"`
	Options          *[]ParameterOption `json:"options"`
	Precision        *int               `json:"precision"`
	Required         bool               `json:"required"`
	ResetOnChange    *ResetOnChange     `json:"reset_on_change,omitempty"`
	Scope            *string            `json:"scope"`
	Template         *ParameterTemplate `json:"template"`
	Type             ToolParameterType  `json:"type"`
}

// ToolParameterForm defines model for ToolParameterForm.
type ToolParameterForm string

// ToolParameterType defines model for ToolParameterType.
type ToolParameterType string

// ToolProviderDeclaration defines model for ToolProviderDeclaration.
type ToolProviderDeclaration struct {
	CredentialsSchema []ProviderConfig     `json:"credentials_schema"`
	Identity          ToolProviderIdentity `json:"identity"`
	OauthSchema       *OAuthSchema         `json:"oauth_schema"`
	Tools             []ToolDeclaration    `json:"tools"`
}

// ToolProviderIdentity defines model for ToolProviderIdentity.
type ToolProviderIdentity struct {
	Author      string       `json:"author"`
	Description I18NObject   `json:"description"`
	Icon        string       `json:"icon"`
	IconDark    string       `json:"icon_dark"`
	Label       I18NObject   `json:"label"`
	Name        string       `json:"name"`
	Tags        *[]PluginTag `json:"tags"`
}

// ToolProviderInstallation defines model for ToolProviderInstallation.
type ToolProviderInstallation struct {
	CreatedAt              time.Time                `json:"created_at"`
	Declaration            *ToolProviderDeclaration `json:"declaration"`
	ID                     string                   `json:"id"`
	PluginID               string                   `json:"plugin_id"`
	PluginUniqueIdentifier string                   `json:"plugin_unique_identifier"`
	Provider               string                   `json:"provider"`
	TenantID               string                   `json:"tenant_id"`
	UpdatedAt              time.Time                `json:"updated_at"`
}

// TenantID defines model for TenantID.
type TenantID = string

// BadRequest defines model for BadRequest.
type BadRequest = DaemonErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = DaemonErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = DaemonErrorResponse

// GetToolParams defines parameters for GetTool.
type GetToolParams struct {
	PluginID string `form:"plugin_id" json:"plugin_id"`
	Provider string `form:"provider" json:"provider"`
}

// ListToolsParams defines parameters for ListTools.
type ListToolsParams struct {
	Page     int `form:"page" json:"page"`
	PageSize int `form:"page_size" json:"page_size"`
}

// AsGetToolSuccessResponse returns the union data inside the GetToolResponse as a GetToolSuccessResponse
func (t GetToolResponse) AsGetToolSuccessResponse() (GetToolSuccessResponse, error) {
	var body GetToolSuccessResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGetToolSuccessResponse overwrites any union data inside the GetToolResponse as the provided GetToolSuccessResponse
func (t *GetToolResponse) FromGetToolSuccessResponse(v GetToolSuccessResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGetToolSuccessResponse performs a merge with any union data inside the GetToolResponse, using the provided GetToolSuccessResponse
func (t *GetToolResponse) MergeGetToolSuccessResponse(v GetToolSuccessResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDaemonErrorResponse returns the union data inside the GetToolResponse as a DaemonErrorResponse
func (t GetToolResponse) AsDaemonErrorResponse() (DaemonErrorResponse, error) {
	var body DaemonErrorResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDaemonErrorResponse overwrites any union data inside the GetToolResponse as the provided DaemonErrorResponse
func (t *GetToolResponse) FromDaemonErrorResponse(v DaemonErrorResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDaemonErrorResponse performs a merge with any union data inside the GetToolResponse, using the provided DaemonErrorResponse
func (t *GetToolResponse) MergeDaemonErrorResponse(v DaemonErrorResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t GetToolResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *GetToolResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsListToolsSuccessResponse returns the union data inside the ListToolsResponse as a ListToolsSuccessResponse
func (t ListToolsResponse) AsListToolsSuccessResponse() (ListToolsSuccessResponse, error) {
	var body ListToolsSuccessResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromListToolsSuccessResponse overwrites any union data inside the ListToolsResponse as the provided ListToolsSuccessResponse
func (t *ListToolsResponse) FromListToolsSuccessResponse(v ListToolsSuccessResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeListToolsSuccessResponse performs a merge with any union data inside the ListToolsResponse, using the provided ListToolsSuccessResponse
func (t *ListToolsResponse) MergeListToolsSuccessResponse(v ListToolsSuccessResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDaemonErrorResponse returns the union data inside the ListToolsResponse as a DaemonErrorResponse
func (t ListToolsResponse) AsDaemonErrorResponse() (DaemonErrorResponse, error) {
	var body DaemonErrorResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDaemonErrorResponse overwrites any union data inside the ListToolsResponse as the provided DaemonErrorResponse
func (t *ListToolsResponse) FromDaemonErrorResponse(v DaemonErrorResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDaemonErrorResponse performs a merge with any union data inside the ListToolsResponse, using the provided DaemonErrorResponse
func (t *ListToolsResponse) MergeDaemonErrorResponse(v DaemonErrorResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ListToolsResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ListToolsResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetTool Get an installed tool provider
	// (GET /plugin/{tenant_id}/management/tool)
	GetTool(c *gin.Context, tenantID TenantID, params GetToolParams)
	// ListTools List installed tool providers
	// (GET /plugin/{tenant_id}/management/tools)
	ListTools(c *gin.Context, tenantID TenantID, params ListToolsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetTool operation middleware
func (siw *ServerInterfaceWrapper) GetTool(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "tenant_id" -------------
	var tenantID TenantID

	err = runtime.BindStyledParameterWithOptions("simple", "tenant_id", c.Param("tenant_id"), &tenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tenant_id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetToolParams

	// ------------- Required query parameter "plugin_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "plugin_id", c.Request.URL.Query(), &params.PluginID, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter plugin_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "provider" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "provider", c.Request.URL.Query(), &params.Provider, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter provider: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTool(c, tenantID, params)
}

// ListTools operation middleware
func (siw *ServerInterfaceWrapper) ListTools(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "tenant_id" -------------
	var tenantID TenantID

	err = runtime.BindStyledParameterWithOptions("simple", "tenant_id", c.Param("tenant_id"), &tenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tenant_id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListToolsParams

	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "page_size", c.Request.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page_size: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListTools(c, tenantID, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/plugin/:tenant_id/management/tools", wrapper.ListTools)
	router.GET(options.BaseURL+"/plugin/:tenant_id/management/tool", wrapper.GetTool)
}

type BadRequestJSONResponse DaemonErrorResponse

type InternalServerErrorJSONResponse DaemonErrorResponse

type UnauthorizedJSONResponse DaemonErrorResponse

type GetToolRequestObject struct {
	TenantID TenantID `json:"tenant_id"`
	Params   GetToolParams
}

type GetToolResponseObject interface {
	VisitGetToolResponse(w http.ResponseWriter) error
}

type GetTool200JSONResponse GetToolResponse

func (t GetTool200JSONResponse) MarshalJSON() ([]byte, error) {
	return GetToolResponse(t).MarshalJSON()
}

func (t *GetTool200JSONResponse) UnmarshalJSON(b []byte) error {
	return (*GetToolResponse)(t).UnmarshalJSON(b)
}

func (response GetTool200JSONResponse) VisitGetToolResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTool400JSONResponse struct{ BadRequestJSONResponse }

func (response GetTool400JSONResponse) VisitGetToolResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetTool401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetTool401JSONResponse) VisitGetToolResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetTool500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetTool500JSONResponse) VisitGetToolResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListToolsRequestObject struct {
	TenantID TenantID `json:"tenant_id"`
	Params   ListToolsParams
}

type ListToolsResponseObject interface {
	VisitListToolsResponse(w http.ResponseWriter) error
}

type ListTools200JSONResponse ListToolsResponse

func (t ListTools200JSONResponse) MarshalJSON() ([]byte, error) {
	return ListToolsResponse(t).MarshalJSON()
}

func (t *ListTools200JSONResponse) UnmarshalJSON(b []byte) error {
	return (*ListToolsResponse)(t).UnmarshalJSON(b)
}

func (response ListTools200JSONResponse) VisitListToolsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListTools400JSONResponse struct{ BadRequestJSONResponse }

func (response ListTools400JSONResponse) VisitListToolsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListTools401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListTools401JSONResponse) VisitListToolsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListTools500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListTools500JSONResponse) VisitListToolsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetTool Get an installed tool provider
	// (GET /plugin/{tenant_id}/management/tool)
	GetTool(ctx context.Context, request GetToolRequestObject) (GetToolResponseObject, error)
	// ListTools List installed tool providers
	// (GET /plugin/{tenant_id}/management/tools)
	ListTools(ctx context.Context, request ListToolsRequestObject) (ListToolsResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// GetTool operation middleware
func (sh *strictHandler) GetTool(ctx *gin.Context, tenantID TenantID, params GetToolParams) {
	var request GetToolRequestObject

	request.TenantID = tenantID
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTool(ctx, request.(GetToolRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTool")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetToolResponseObject); ok {
		if err := validResponse.VisitGetToolResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTools operation middleware
func (sh *strictHandler) ListTools(ctx *gin.Context, tenantID TenantID, params ListToolsParams) {
	var request ListToolsRequestObject

	request.TenantID = tenantID
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListTools(ctx, request.(ListToolsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTools")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListToolsResponseObject); ok {
		if err := validResponse.VisitListToolsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fpbc+O2Ff4rGDRvhSx7c2mqNyduEqWZtWftzHTqUTkweSRhFwS4AOi11qP/3gHAC0BSF8rr7fRJFAng",
	"3L5z8OHyjFOZF1KAMBrPnnFBFc3BgHL/7kBQYeZX9pkJPMMFNWtMsKA54Bk27nPCMkywgo8lU5DhmVEl",
	"EKzTNeTUdsyZ+APEyqzx7IJgsylsV20UEyu83W5tV11IocGJ/Ilm7+BjCdrYf6kUBoR7pEXBWUoNk2L6",
	"Xkth37VCvlGwxDP8l2lrztR/1dMrCrkU/1BKqneVKC84A50qVtgh8QzPxSPlLEPKi0etK87wluC5MKAE",
	"5begHkG50b62hndrQNqJR6kseYaENMgOx8EAMmuodXcK/yloadZSsc82Kv8bX2auObq8maMPsDnDtmU1",
	"lJX0sxRLtrquej1jmmXMPlN+o2QByjALiiXlGgguglfPmNMH4Ie0nV/8KK4f3kNqrEMeKS/BIZI+NYh8",
	"8zdyAKEhtu+rQUglf9E0l40Yb9Sde/2MQZS57achVWAmTBSlwQQbeGr/aOC2L8EPUnKgAhOcywz4xH+Q",
	"ChMbsuivUnRzb6TkehFoUStN8FCgxnk4lVntLZZbIyatc5gwsAJlBWXUONRUX0TJOSb4abKSk+oVFZvw",
	"zUR/YMVEFl6NSSHtYMrXjS3BOWhNV05yjKnfb6/fTkBYtRpggbUPZWAo45ogZR8EZIhqRJF3BlpK5ZKE",
	"GvbAODObM3woyM70VpXKyKFg/wrmTkoeulgKuF7i2f1+aFYdb8s0Ba3bXCIn5N+iVaQ73mkhT6Ww9fd8",
	"X7z3aWk1uVHykWWg5kIbyrkrNjiObyUGa6/0FwxLkPjjPAAi+fO2WyPO33x7oEgQ/J4mv98Mduw1LUzy",
	"07vjmn5eJ79RoY9p3PGVN2TIN38w7aCix4O26frFYLtzxNcDLjOQ65cguC5rtgR/NUS/LTmnDxxiZB8X",
	"tmgajCv1dhHX6vnFj2/bGfP6sjTr24YYjAkIZyBM0pKKo7xee9xPoa2v7ytnE6+0BU6qIANhGOX61aR0",
	"gxXZNKjCoh2rCl2g8k1NKC9LI38FAYqasUA3HVpRKJkXJmFCG1WmDqGLQ6BzX4/T9CRqxlLfpVfNXsTZ",
	"TuZoxCs0lFSNnXeQF3x8NEDYlMwCY2sG1y/HvuV+t/NyxcQdXcXEkarULrpY7kuExa60peUTULMGywaX",
	"TFCRuvoBmq0sgTSKPjrjtUwZtQ8CPmlXazKWuheFkpnFzCMzFvSQlX5JYIloqZnwBQwsO7O0KreLB4JL",
	"Y0mUdQDBdOXfKbrCBMtKG6PYytbcIVrayb1x7s5gSUvup3SxqQpfV0RQ3/IHV/n7wRkogjHXvEQ6pZwq",
	"1OY4qqQTJBWy3dCnNQgkZP0BMY1SZ1apIDt7EQleAy8OJcrAjHBajuUlN6zgMATjeq1/DFnx1uij63C0",
	"+rN60Ke57+dWZTtLf8FpCmvJM1Cn+ahNzCGDFWgwiRRJuqbCT+v7RLyzza/Fz76xW9/KIvDlfe2hwIK6",
	"ih/2jltGbgkuFd83ZKfauJhVYmqFghakyaQ2aAEM2sLpYOiFx24fKqaxI0IQjOXSARB+6NMtS82uIOVU",
	"0RMmpyjPD3PAq6C5zUuqE1UKw3JI4q2yPo6YKxxmc4yYed3WplFpijKkTsPW+W22XhRirY7nunW34+lQ",
	"Y19cPCMVdnpsCEBdf48L7LrMqRhX+DjPx1ILL8V33WXDPAj8CAP8bt1BhU4q8XURL6gxoOwM9597Ovl8",
	"Ofn3+eTvyWTx128OLlUq9UhdXHZvgMV4Gu0EmawCbryXyA8S6i0JiUJnXhcb9Pvt9VvkKCJBTKS8zJhY",
	"uRmdIId4TRAVGfIG6Xa3KCq7jluEO3YNnYuz5iUsYClVPip5f7EdbJmyKE1GlLoXcwjO8668obJu31ur",
	"qF0kZ7J84BC4t/FqM1HmTIzuchqbOZBzY7lNdwW1bylbKEiZjrx232xcBO2+Em2JXfMd2cdjgmXTUd5o",
	"1llHkqAI3Z4LDVOdhrH0kN+jQS6r+oiN+FFchgJDQ+pkwelRHZGnNpwtbA6WyV+qVG9WffUmQ6vt4Hqq",
	"76BwkD3lqjlz6BxMLJkzwv7o/rFD/1jCFbRsI2jO0kkzaI3xpiima0g/PMgnv8VV7XTBRDn07TSsWiye",
	"zvZeYZeoJaJjCF6zlxgSPTulJsedu4U7cVYVKfk4ghf6sGfLbmY34MCO4rUye3c2Bl3wSvTo5Gmv3rc6",
	"ML5tlmRUffhSe1ynkDOCDV2NmI6anaWj6X2X78W10vkq9EVbgp1iOwve0J766JymBrKEmpga2Hpilxl4",
	"EBNRBTk2WztJw7LBkBfOucn+r6VgH0tIfGotmSfG/caV4MGP7XWLoa9lkY10Sy/rfb7Xo0RDkuiyR6Pm",
	"HvNCv8QB6GNj66ahUjGzcTXOB9ofGl0W7J+waW6grIF6wdUdlH9NLgs2sS3aouZ7uGsJTCxlfxnw293d",
	"DUqlMIqmRrsTYuYBCRmy5QzVFqKM6VQ+gvKnxsxYYomv2HKDfE6hq+aKAyb4EZQncvj87OLs3DNHELRg",
	"eIa/da+Iu0TjDJx6D02fG99upzkVdAU5CDO1ithmK/BnPQV4B84zPKvPe+Pl9q6DoLbJtLnSsyWVRz+W",
	"oDatQ8OonXqpZ9fQLWxOHXnRuS705vz8i91t6Z7l77iBE+NDKkTr2whNhPy9hHB5SVHOtLZPdU93R+c7",
	"r/6QVo2Z0+BKlOtycbhLdPdnS/D3x8gZuuHkUrPMc6o2HnSIil254hofgWm9E9TNafArwNofnuzFnb/m",
	"MnDLZd+giWafD4xcX6B58/0PZL+c14R3/9x/COBhQPU+dP8/4te6YBd6tXdHPQ850MUz0P1iu9j+NwAA",
	"//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
