// Code generated by controller generator. DO NOT EDIT.

package plugin_daemon

import (
	"github.com/langgenius/dify-plugin-daemon/internal/core/session_manager"
	"github.com/langgenius/dify-plugin-daemon/internal/utils/stream"
	"github.com/langgenius/dify-plugin-daemon/pkg/entities/datasource_entities"
	"github.com/langgenius/dify-plugin-daemon/pkg/entities/requests"
)

func DatasourceValidateCredentials(
	session *session_manager.Session,
	request *requests.RequestValidateDatasourceCredentials,
) (
	*stream.Stream[datasource_entities.DataSourceValidateCredentialsResponse], error,
) {
	return GenericInvokePlugin[requests.RequestValidateDatasourceCredentials, datasource_entities.DataSourceValidateCredentialsResponse](
		session,
		request,
		1,
	)
}

func DatasourceGetWebsiteCrawl(
	session *session_manager.Session,
	request *requests.RequestInvokeDatasourceFirstStep,
) (
	*stream.Stream[datasource_entities.DataSourceResponseChunk], error,
) {
	return GenericInvokePlugin[requests.RequestInvokeDatasourceFirstStep, datasource_entities.DataSourceResponseChunk](
		session,
		request,
		1,
	)
}

func DatasourceGetOnlineDocumentPages(
	session *session_manager.Session,
	request *requests.RequestInvokeDatasourceFirstStep,
) (
	*stream.Stream[datasource_entities.DataSourceInvokeFirstStepResponse], error,
) {
	return GenericInvokePlugin[requests.RequestInvokeDatasourceFirstStep, datasource_entities.DataSourceInvokeFirstStepResponse](
		session,
		request,
		1,
	)
}

func DatasourceGetOnlineDocumentPageContent(
	session *session_manager.Session,
	request *requests.RequestInvokeOnlineDocumentDatasourceGetContent,
) (
	*stream.Stream[datasource_entities.DataSourceResponseChunk], error,
) {
	return GenericInvokePlugin[requests.RequestInvokeOnlineDocumentDatasourceGetContent, datasource_entities.DataSourceResponseChunk](
		session,
		request,
		1,
	)
}
